apiVersion: v1
kind: ConfigMap
metadata:
  name: app-conf
data:
  env: |

    APP_NAME=docker-laravel
    APP_ENV=local
    APP_KEY=base64:491bzLYHOjd9K8K8DlPOKKP7soOdA9bQdOsSUNFZAGI=
    APP_DEBUG=true
    APP_LOG_LEVEL=debug
    APP_URL=http://localhost

    DB_CONNECTION=mysql
    DB_HOST=mysql-service
    DB_PORT=3306
    DB_DATABASE=laravel
    DB_USERNAME=root

    BROADCAST_DRIVER=log
    CACHE_DRIVER=file
    SESSION_DRIVER=file
    QUEUE_DRIVER=sync

    REDIS_HOST=redis-service
    REDIS_PASSWORD=null
    REDIS_PORT=6379 

    MAIL_DRIVER=smtp
    MAIL_HOST=smtp.mailtrap.io
    MAIL_PORT=2525
    MAIL_USERNAME=null
    MAIL_PASSWORD=null
    MAIL_ENCRYPTION=null

    PUSHER_APP_ID=
    PUSHER_APP_KEY=
    PUSHER_APP_SECRET=
